# Generated by Django 6.0 on 2025-12-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('line', models.CharField(default='3호선', max_length=10)),
                ('is_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
