# Generated by Django 6.0 on 2025-12-22 02:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subway', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Episode',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('episode_num', models.IntegerField(default=1)),
        #         ('title', models.CharField(default='제목 없음', max_length=200)),
        #         ('subtitle', models.CharField(blank=True, default='', max_length=200, null=True)),
        #         ('history_summary', models.TextField()),
        #         ('last_viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
        #         ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subway.station')),
        #     ],
        #     options={
        #         'unique_together': {('station', 'episode_num')},
        #     },
        # ),
        migrations.CreateModel(
            name='EpisodeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='episode_images/')),
                ('caption', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stories.episode')),
            ],
        ),
    ]
