# Generated by Django 5.2.8 on 2025-12-24 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
        ('subway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subway.station'),
        ),
    ]
