# Generated by Django 5.2.8 on 2025-12-24 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_episode_station'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cut',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='episode',
            name='webtoon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='stories.webtoon'),
        ),
    ]
