# Generated by Django 6.0 on 2026-01-03 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='is_leader_approved',
            field=models.BooleanField(default=False, verbose_name='팀장 승인 여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='leader_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='팀장 고유 번호'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.CreateModel(
            name='TeamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('APPROVED', '승인'), ('REJECTED', '반려')], default='PENDING', max_length=10, verbose_name='진행 상태')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='신청 일시')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리 일시')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL, verbose_name='대상 팀장')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL, verbose_name='신청 유저')),
            ],
            options={
                'verbose_name': '팀 가입 요청',
                'db_table': 'team_requests',
                'unique_together': {('user', 'leader')},
            },
        ),
    ]
