# Generated by Django 6.0 on 2026-01-03 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_is_leader_approved_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='oauthaccount',
            table='oauth_accounts',
        ),
        migrations.CreateModel(
            name='MembershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('LEADER', '팀장 신청'), ('MEMBER', '팀원 신청')], max_length=10)),
                ('applicant_name', models.CharField(max_length=50, verbose_name='신청자명')),
                ('team_name', models.CharField(max_length=100, verbose_name='팀명')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='신청 사유')),
                ('target_leader_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='팀 고유번호')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('APPROVED', '승인'), ('REJECTED', '반려')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'membership_requests',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='팀명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_managed_team', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team_members',
            },
        ),
        migrations.DeleteModel(
            name='TeamRequest',
        ),
        migrations.AddIndex(
            model_name='membershiprequest',
            index=models.Index(fields=['user', 'status'], name='membership__user_id_c1f728_idx'),
        ),
        migrations.AddIndex(
            model_name='membershiprequest',
            index=models.Index(fields=['target_leader_code'], name='membership__target__70ec79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'user')},
        ),
    ]
