# Generated by Django 6.0 on 2026-01-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_oauthaccount_table_membershiprequest_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiprequest',
            name='reason',
        ),
        migrations.AddField(
            model_name='team',
            name='team_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='팀 고유번호'),
        ),
    ]
