# Generated by Django 6.0 on 2026-01-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_membershiprequest_reason_team_team_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_leader_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='leader_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
